version: "3.7"
services:
  web:
    build:
      context: .
    command: bash -c "alembic upgrade head && uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 8111"
    volumes:
      - .:/app
    ports:
      - "8111:8111"

  postgres:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local