"""empty message

Revision ID: 0298f0dcf4d5
Revises: ebd4f0ef56a5
Create Date: 2023-04-19 23:01:16.357483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0298f0dcf4d5'
down_revision = 'ebd4f0ef56a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film_genre',
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('film_genre')
    # ### end Alembic commands ###
